version: '3.8'
services:
  redpanda:
    command:
      - redpanda start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda:33145
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.13
    container_name: redpanda
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - redpanda_network

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.2.3
    networks:
      - redpanda_network
    ports:
      - 8080:8080
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - CONFIG_FILEPATH=/etc/console/console.yml
    volumes:
      - ./console.yml:/etc/console/console.yml

volumes:
  redpanda_data:

networks:
  redpanda_network: